-- schema.sql 실행 후 1회 실행: 원본 엑셀 기반 33개 실행 항목 초기 데이터
insert into public.tasks(source_key,sort_order,no_text,process,item,spec,unit,qty,vendor,primary_action,action_tags,source_data,status,progress) values
('task-5-1',1,'1','Uncoiler','senso báo hết liệu
자재 소진 감지 센서','BF5R D1-N','set',2,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 5, "scenario": {"H": null, "I": null, "J": 2, "K": null}, "spare": null, "note": "c2 ; 2 bộ senso", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "표준 센서 사양(BF5R D1-N)이 명시된 SMWORLD 공급 항목.", "deadlines": ["9/30"], "images": ["assets/images/image5.webp", "assets/images/image6.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-6-2',2,'2','Uncoiler','motor cuốn giấy
간지용 모터','','Ea',1,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 6, "scenario": {"H": null, "I": null, "J": 1, "K": null}, "spare": null, "note": "Lắp thêm c2 (1 con bị cháy)", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "간지용 모터 1EA. SMWORLD 공급 목록에 명시.", "deadlines": ["9/30"], "images": ["assets/images/image4.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-7-3',3,'3','Feeder','đệm nhựa
플라스틱 와셔','','Ea',1,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 7, "scenario": {"H": null, "I": null, "J": 1, "K": null}, "spare": null, "note": "Thiếu,khi nắp line", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "누락 설치분 플라스틱 와셔 1EA. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image7.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-8-4',4,'4','Dòng dọc
롤러','Con năn dòng dọc
롤러','','Ea',15,'SMWORLD','return','["return", "sm_action"]'::jsonb,'{"excelRow": 8, "scenario": {"H": null, "I": null, "J": 15, "K": null}, "spare": null, "note": "Đã gửi về hàn chưa thấy gửi lại roy vina", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "롤러 15EA가 SMWORLD로 발송되었으나 반송되지 않았다고 명시. 기존품 회수/재제작/대체 공급 결정 필요.", "deadlines": ["9/30"], "images": ["assets/images/image9.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 발송 롤러 15EA 위치 확인 → 반송일 확정. 반송 불가 시 재제작/대체공급 결정", "primaryActionLabel": "회수·반송 조치", "actionTagLabels": ["회수·반송 조치", "SM월드 해결 / 조치"]}'::jsonb,'blocked',0),
('task-9-5',5,'5','침적탈지','Máy bơm
펌프','220v-250w','Ea',12,'Roy Vina','roy_self','["roy_self"]'::jsonb,'{"excelRow": 9, "scenario": {"H": null, "I": null, "J": 8, "K": 1}, "spare": 3, "note": "침적탈지 추가 : 1 개\nC2침적탈지 추가 : 3 개\nC2 라인 Sus용, Cu용 추가: 2 개\nC2 nikel s/t 추가  : 1 개\nC2 활성화 추가  : 1 개\n추가 표면 처리  : 1개\n예비 설비  : 3 개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "220V-250W 표준 펌프. Roy 시트에 수량 및 사용처가 구체적으로 정리됨.", "deadlines": ["9/30"], "images": ["assets/images/image39.webp"], "source": "총 필요량", "exception": false, "nextAction": "현지 구매/조달 가능 여부 확인 → 발주·준비 → 입고/설치", "primaryActionLabel": "베트남(로이비나) 자체 해결", "actionTagLabels": ["베트남(로이비나) 자체 해결"]}'::jsonb,'not_started',0),
('task-10-6',6,'6','Tẩy rửa
탈지','dây điện xanh
녹색 전선','1c*8mm','m',168,'Roy Vina','roy_self','["roy_self"]'::jsonb,'{"excelRow": 10, "scenario": {"H": null, "I": null, "J": 168, "K": null}, "spare": null, "note": "탈지 : 4개 x 12m\nNikel s/t : 12m x 3개\nSn 활성화 : 12 X 2개\nNi c1: 12m x 5개\nNi c2: 12m x 5개\nNi c3: 12m x 5개\nSn c2: 12m x 5개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "1C×8mm 녹색 전선. 일반 구매자재로 Roy 현지 조달 항목으로 정리.", "deadlines": ["9/30"], "images": ["assets/images/image37.webp"], "source": "총 필요량", "exception": false, "nextAction": "현지 구매/조달 가능 여부 확인 → 발주·준비 → 입고/설치", "primaryActionLabel": "베트남(로이비나) 자체 해결", "actionTagLabels": ["베트남(로이비나) 자체 해결"]}'::jsonb,'not_started',0),
('task-11-7',7,'7','Tẩy rửa
탈지','dây điện đỏ
빨간색 전선','1c*8mm','m',408,'Roy Vina','roy_self','["roy_self"]'::jsonb,'{"excelRow": 11, "scenario": {"H": null, "I": null, "J": 408, "K": null}, "spare": null, "note": "탈지: 4개 x 12m x 3 셀\nnikel s/t : 12m x 4개\nHTH SN : 12 X 2개\nNi c1: 12m x 8개\nNi c2: 12m x 4개  x 32바스켓\nNi c3: 12m x 8개\nSn c2: 12m x 16개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "1C×8mm 빨간색 전선. 일반 구매자재로 Roy 현지 조달 항목으로 정리.", "deadlines": ["9/30"], "images": ["assets/images/image38.webp"], "source": "총 필요량", "exception": false, "nextAction": "현지 구매/조달 가능 여부 확인 → 발주·준비 → 입고/설치", "primaryActionLabel": "베트남(로이비나) 자체 해결", "actionTagLabels": ["베트남(로이비나) 자체 해결"]}'::jsonb,'not_started',0),
('task-12-8',8,'8','Tẩy rửa
탈지','Trân ren ống dẫn khí và nước
에어노즐 1','','Ea',104,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 12, "scenario": {"H": null, "I": null, "J": 104, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "탈지부 에어노즐 부품 1. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image12.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-13-9',9,'9','Tẩy rửa
탈지','Thân ống dẫn khí và nước
에어노즐2','','Ea',1560,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 13, "scenario": {"H": null, "I": null, "J": 1560, "K": null}, "spare": null, "note": "수량 : 마디", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "탈지부 에어노즐 부품 2. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image14.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-14-10',10,'10','Tẩy rửa
탈지','Vòi phun ống dãn khí và nước
에어노즐3','','Ea',104,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 14, "scenario": {"H": null, "I": null, "J": 104, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "탈지부 에어노즐 부품 3. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image13.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-15-11',11,'11','Tẩy rửa
탈지','máy chỉnh lưu
정류기','탈지 220v (100a-15v)
Nikel s/t 220v (100a-15v)
NI 1,2,3,4 220v (200a-15v)
Ni #3 C1,3 220v (200a-15v)
Hth sn 220v (10a-15v)
Sn 220v (100a-15v)','Ea',15,'SMWORLD','stock','["stock", "sm_action", "scope"]'::jsonb,'{"excelRow": 15, "scenario": {"H": null, "I": 6, "J": 9, "K": null}, "spare": null, "note": "탈지 220v (100a-15v) : 1대\nNikel s/t 220v (100a-15v) : 1 대\nNi 1,2,3,4 220v (200a-15v) : 4대\nNi #3 c1,3 220v (200a-15v) : 2대\n활성화 Sn 220v (10a-15v) : 1대\nSn 220v (100a-15v) : 6대", "royStock": 8, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요 15EA와 Roy Vina 보유재고 8EA가 함께 표기됨. 재고가 총 필요량에 포함되는지, 순발주 수량이 몇 대인지 확정 필요.", "deadlines": ["9/10", "9/30"], "images": ["assets/images/image15.webp"], "source": "총 필요량", "exception": false, "nextAction": "Roy 보유 정류기 8EA의 사양·상태·사용 가능 여부 확인 → 총 15EA에서 차감 여부 결정 → 순발주량 확정", "primaryActionLabel": "재고 확인·활용", "actionTagLabels": ["재고 확인·활용", "SM월드 해결 / 조치", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-16-12',12,'12','Tẩy rửa
탈지','Tấm cực + inox
서스전극','350 x 130 x2','Ea',12,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 16, "scenario": {"H": null, "I": null, "J": 8, "K": 4}, "spare": null, "note": "양극판 4개/셀 x 3 셀", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "SUS 전극 350×130×2, 12EA. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image10.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-17-13',13,'10','Tẩy rửa
탈지','Giỏ đựng annode nikel (baket) + vải bọc mùn giỏ đựng
니켈 양극 바스켓 및 슬러지 방지용 아노드 백 구매 요청 건','300 x 100 x 30','set',84,'SMWORLD','scope','["scope", "sm_action", "uline", "master_fix"]'::jsonb,'{"excelRow": 17, "scenario": {"H": 16, "I": 16, "J": 44, "K": 8}, "spare": null, "note": "C2 Ni s/t : 4 개\nNi C1: 8 개\nNi C2: 32 개\nNi C3: 8 개\nSn C1 : 16 개\nSn C2 : 16 개", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요량 84SET이나 SMWORLD 시트는 68SET. U자 라인 16SET 추가분까지 SMWORLD 공급 범위인지 확인 필요.", "deadlines": ["9/10", "9/30", "일정 미기재(U자)"], "images": ["assets/images/image11.webp"], "source": "총 필요량", "exception": false, "nextAction": "84SET(총 필요량) vs 68SET(SMWORLD) 차이 16SET 확인 → U자 라인 추가분 공급주체와 납기 확정", "primaryActionLabel": "수량·공급범위 확정", "actionTagLabels": ["수량·공급범위 확정", "SM월드 해결 / 조치", "U자 라인 추가분 확정", "총괄표 누락·불일치 정리"]}'::jsonb,'review',0),
('task-18-14',14,'14','Nikel','전극용 동 블록
Đế đồng tiếp điểm','','set',28,'Roy Vina','drawing','["drawing", "local_fab"]'::jsonb,'{"excelRow": 18, "scenario": {"H": null, "I": 12, "J": null, "K": 6}, "spare": 10, "note": "", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "원본 비고에 “도면 받아 로이비나 가공” 명시. Roy 자체 가공 가능하나 제작도면 지원이 선행되어야 함.", "deadlines": ["9/10", "9/30"], "images": ["assets/images/image29.webp", "assets/images/image30.webp", "assets/images/image35.webp"], "source": "총 필요량", "exception": false, "nextAction": "전극용 동 블록 가공도면 작성·검토 → Roy Vina 발송 → 28SET 현지 가공", "primaryActionLabel": "가공도면 발송 필요", "actionTagLabels": ["가공도면 발송 필요", "베트남 현지 가공 진행"]}'::jsonb,'blocked',0),
('task-19-15',15,'15','Nikel','Máy bơm
펌프','','ea',7,'Roy Vina','roy_self','["roy_self"]'::jsonb,'{"excelRow": 19, "scenario": {"H": null, "I": 2, "J": 3, "K": 1}, "spare": 1, "note": "Nikel C1 ,C2,C3 : 4개\nSn C2 : 2개\n예비 설비 : 1개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "Ni/Sn 공정용 펌프 7EA. Roy 시트에 수량/예비분이 정리됨.", "deadlines": ["9/10", "9/30"], "images": ["assets/images/image28.webp", "assets/images/image32.webp", "assets/images/image33.webp"], "source": "총 필요량", "exception": false, "nextAction": "현지 구매/조달 가능 여부 확인 → 발주·준비 → 입고/설치", "primaryActionLabel": "베트남(로이비나) 자체 해결", "actionTagLabels": ["베트남(로이비나) 자체 해결"]}'::jsonb,'not_started',0),
('task-20-16',16,'16','Nikel','Đế tiếp điện đồng
컨택용 받침 블럭','','ea',11,'Roy Vina','drawing','["drawing", "local_fab"]'::jsonb,'{"excelRow": 20, "scenario": {"H": null, "I": 6, "J": null, "K": 3}, "spare": 2, "note": "", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "원본 비고에 “도면 받아 로이비나 가공” 명시. Roy 자체 가공 + 도면 지원 필요.", "deadlines": ["9/10", "9/30"], "images": ["assets/images/image34.webp"], "source": "총 필요량", "exception": false, "nextAction": "컨택용 받침 블럭 가공도면 작성·검토 → Roy Vina 발송 → 11EA 현지 가공", "primaryActionLabel": "가공도면 발송 필요", "actionTagLabels": ["가공도면 발송 필요", "베트남 현지 가공 진행"]}'::jsonb,'blocked',0),
('task-21-17',17,'17','Nikel','máng chắn nikel 
차폐막','','ea',18,'Roy Vina','uline','["uline", "scope", "local_fab"]'::jsonb,'{"excelRow": 21, "scenario": {"H": 8, "I": null, "J": 10, "K": null}, "spare": null, "note": "C1 nikel 3 : 2개\nC2 nikel 1,2,3 : 6개\nC3 nikel 3 : 2개\nSn c1: 4개\nSn c2 : 4개", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요량은 18EA(U자 라인 8 + 현 구성 10)인데 Roy 시트는 10EA. U자 라인 8EA의 현지 제작 범위/일정 확정 필요.", "deadlines": ["9/30", "일정 미기재(U자)"], "images": ["assets/images/image36.webp"], "source": "총 필요량", "exception": false, "nextAction": "현 구성 10EA + U자 라인 8EA 범위 확정 → 도면/치수 확정 후 Roy Vina 제작 일정 수립", "primaryActionLabel": "U자 라인 추가분 확정", "actionTagLabels": ["U자 라인 추가분 확정", "수량·공급범위 확정", "베트남 현지 가공 진행"]}'::jsonb,'review',0),
('task-22-18',18,'18','Sấy khô
건조','Senso đo nhiêt đô khoang sấy khô
건조실용 온도 센서.','','Ea',1,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 22, "scenario": {"H": null, "I": null, "J": 1, "K": null}, "spare": null, "note": "C2:1 개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "건조실용 온도센서 1EA. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image23.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-23-19',19,'19','Reflow','Vỏ hộp bảo vệ lò reflow
리플로우 오븐 보호 케이스','350 x 580 x 1080','set',1,'SMWORLD','design','["design", "sm_action", "uline"]'::jsonb,'{"excelRow": 23, "scenario": {"H": 1, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "총 필요량 시트에는 U자 라인용 1SET이 있으나 SMWORLD 시트 수량은 0. 외곽 케이스 치수/설계 및 제작 주체 확정 필요.", "deadlines": ["일정 미기재(U자)"], "images": ["assets/images/image1.webp"], "source": "총 필요량", "exception": false, "nextAction": "리플로우 보호 케이스 350×580×1080 상세 도면/장착 인터페이스 확정 → 제작주체와 납기 결정", "primaryActionLabel": "설계·사양 지원 필요", "actionTagLabels": ["설계·사양 지원 필요", "SM월드 해결 / 조치", "U자 라인 추가분 확정"]}'::jsonb,'blocked',0),
('task-24-20',20,'20','Reflow','Quạt gió,ra nhiệt
송풍기 /히팅','','ea',3,'Roy Vina','stock','["stock", "scope"]'::jsonb,'{"excelRow": 24, "scenario": {"H": 1, "I": null, "J": null, "K": null}, "spare": 2, "note": "1 개 부족\n2 개 재고", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요 3EA, 예비부품 2EA 표기와 비고의 “1개 부족 / 2개 재고”가 함께 존재. 실제 보유/추가구매 수량 재확인 필요.", "deadlines": ["일정 미기재(U자)"], "images": ["assets/images/image40.webp", "assets/images/image41.webp"], "source": "총 필요량", "exception": false, "nextAction": "송풍기 실제 재고 2EA 실사 → 부족 1EA 여부 확정 → 현지 추가구매", "primaryActionLabel": "재고 확인·활용", "actionTagLabels": ["재고 확인·활용", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-25-21',21,'21','Reflow','Tủ điều khiển
제어 패널','','set',1,'SMWORLD','design','["design", "sm_action", "uline"]'::jsonb,'{"excelRow": 25, "scenario": {"H": 1, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "총 필요량 시트에는 U자 라인용 제어패널 1SET이 있으나 SMWORLD 시트는 0. 전장/I/O/인터록 사양과 제작 주체 지원 필요.", "deadlines": ["일정 미기재(U자)"], "images": ["assets/images/image2.webp", "assets/images/image3.webp"], "source": "총 필요량", "exception": false, "nextAction": "제어패널 I/O, 전원, 인터록, 판넬 치수 확정 → 전장도면/제작주체 결정 → U자 라인 납기 반영", "primaryActionLabel": "설계·사양 지원 필요", "actionTagLabels": ["설계·사양 지원 필요", "SM월드 해결 / 조치", "U자 라인 추가분 확정"]}'::jsonb,'blocked',0),
('task-26-22',22,'22','Reflow','jig tiếp điện
SUS재질 컨택 세트
(서스롤러 제외)','','set',4,'SMWORLD','uline','["uline", "sm_action", "scope"]'::jsonb,'{"excelRow": 26, "scenario": {"H": 2, "I": null, "J": 2, "K": null}, "spare": null, "note": "Reflow 앞/두 각 2개씩/Line", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 4SET = U자 라인 2 + 현 구성 2. SMWORLD 시트는 2SET만 반영되어 U자 라인 추가 2SET 공급범위 확인 필요.", "deadlines": ["9/30", "일정 미기재(U자)"], "images": ["assets/images/image22.webp"], "source": "총 필요량", "exception": false, "nextAction": "현 구성 2SET + U자 라인 2SET 여부 확인 → SMWORLD 공급범위 4SET으로 확정", "primaryActionLabel": "U자 라인 추가분 확정", "actionTagLabels": ["U자 라인 추가분 확정", "SM월드 해결 / 조치", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-27-23',23,'23','Reflow','Quạt gió
송풍기','120x120mm 0.14A 220v AC','ea',4,'Roy Vina','uline','["uline", "scope"]'::jsonb,'{"excelRow": 27, "scenario": {"H": 4, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요량 4EA가 모두 U자 라인 시나리오에만 존재하고 Roy 시트 수량은 0. U자 라인 확정 후 현지 조달 일정 결정 필요.", "deadlines": ["일정 미기재(U자)"], "images": ["assets/images/image31.webp", "assets/images/image20.webp"], "source": "총 필요량", "exception": false, "nextAction": "U자 라인 4EA 필요 여부 확정 → Roy Vina 현지 조달 가능 사양 확인 → 구매 일정 확정", "primaryActionLabel": "U자 라인 추가분 확정", "actionTagLabels": ["U자 라인 추가분 확정", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-28-24',24,'24','Recoiler','Đỡ liệu đầu line
부품받침','','set',16,'SMWORLD','uline','["uline", "sm_action", "scope"]'::jsonb,'{"excelRow": 28, "scenario": {"H": 8, "I": null, "J": 8, "K": null}, "spare": null, "note": "con lăn thai đổi từ pvc sang inox\n롤러를 PVC에서 SUS(스텐레스)로 교체", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 16SET = U자 라인 8 + 현 구성 8. SMWORLD 시트는 8SET만 반영. PVC→SUS 변경 포함 추가 8SET 범위 확인 필요.", "deadlines": ["9/30", "일정 미기재(U자)"], "images": ["assets/images/image16.webp"], "source": "총 필요량", "exception": false, "nextAction": "현 구성 8SET + U자 라인 8SET 확인 → PVC→SUS 변경사양 포함 SMWORLD 제작 16SET 여부 확정", "primaryActionLabel": "U자 라인 추가분 확정", "actionTagLabels": ["U자 라인 추가분 확정", "SM월드 해결 / 조치", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-29-25',25,'25','Recoiler','senso cảm biến cuốn liệu
자재 권취 감지 센서','','set',1,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 29, "scenario": {"H": null, "I": null, "J": 1, "K": null}, "spare": null, "note": "c2: 1 개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "Recoiler 자재 권취 감지 센서 1SET. SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image21.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-30-26',26,'26','Recoiler','Camera','','set',2,'SMWORLD','sm_action','["sm_action"]'::jsonb,'{"excelRow": 30, "scenario": {"H": null, "I": null, "J": 1, "K": 1}, "spare": null, "note": "c2: 1 개\nc3: 1 개", "royStock": null, "sourceStatus": "self", "sourceStatusLabel": "자력 진행", "reason": "비전/카메라 2SET(C2 1, C3 1). SMWORLD 공급 목록.", "deadlines": ["9/30"], "images": ["assets/images/image19.webp"], "source": "총 필요량", "exception": false, "nextAction": "SMWORLD 공급/제작 범위 확인 → 준비·제작 → 입고/설치", "primaryActionLabel": "SM월드 해결 / 조치", "actionTagLabels": ["SM월드 해결 / 조치"]}'::jsonb,'not_started',0),
('task-31-27',27,'27','con lăn kéo giữa line
중간피더','con lăn kéo giữa line
중간피더','','set',1,'SMWORLD','design','["design", "sm_action"]'::jsonb,'{"excelRow": 31, "scenario": {"H": null, "I": null, "J": 1, "K": null}, "spare": null, "note": "đế,trục,con lăm chuyển động ,ngày trượt ,cảm biến,động cơ, biến tần\n베이스, 샤프트, 이동 롤러, 슬라이드 레일, 센서, 모터, 인버터", "royStock": null, "sourceStatus": "support", "sourceStatusLabel": "지원 필요", "reason": "중간피더 1SET은 베이스·샤프트·이동롤러·슬라이드레일·센서·모터·인버터 일체. 현장 치수/인터페이스 및 기구 설계 지원 필요.", "deadlines": ["9/30"], "images": ["assets/images/image17.webp", "assets/images/image18.webp"], "source": "총 필요량", "exception": false, "nextAction": "현장 장착공간/레일·축·모터·센서·인버터 인터페이스 측정 → 기구도면 확정 → SMWORLD 제작", "primaryActionLabel": "설계·사양 지원 필요", "actionTagLabels": ["설계·사양 지원 필요", "SM월드 해결 / 조치"]}'::jsonb,'blocked',0),
('task-32-28',28,'28','Sn c1-cnt','túi vải bọc bên ngoài giỏ mạ
외부 바구니를 덮는 천 가방','L530 X H130 X W30','',4,'SMWORLD','scope','["scope", "sm_action"]'::jsonb,'{"excelRow": 32, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요수량은 있으나 총 필요량 시트의 시나리오별 배분이 비어 있음. 사용 시점/적용 라인 확정 필요.", "deadlines": ["일정 미기재"], "images": ["assets/images/image25.webp"], "source": "총 필요량", "exception": false, "nextAction": "최종 수량/적용라인 확정 → 공급주체 확인 → 발주수량 확정", "primaryActionLabel": "수량·공급범위 확정", "actionTagLabels": ["수량·공급범위 확정", "SM월드 해결 / 조치"]}'::jsonb,'review',0),
('task-33-29',29,'29','Sn c3-cnt','túi vải bọc bên ngoài giỏ mạ
외부 바구니를 덮는 천 가방','L310 X H120 X W40','',12,'SMWORLD','scope','["scope", "sm_action"]'::jsonb,'{"excelRow": 33, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요수량은 있으나 시나리오별 배분이 비어 있음. 사용 시점/적용 라인 확정 필요.", "deadlines": ["일정 미기재"], "images": ["assets/images/image25.webp"], "source": "총 필요량", "exception": false, "nextAction": "최종 수량/적용라인 확정 → 공급주체 확인 → 발주수량 확정", "primaryActionLabel": "수량·공급범위 확정", "actionTagLabels": ["수량·공급범위 확정", "SM월드 해결 / 조치"]}'::jsonb,'review',0),
('task-34-30',30,'30','NIKEL FFC','túi vải bọc bên ngoài giỏ mạ
외부 바구니를 덮는 천 가방','L670 X H120 X W40','',3,'SMWORLD','scope','["scope", "sm_action"]'::jsonb,'{"excelRow": 34, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요수량은 있으나 시나리오별 배분이 비어 있음. 사용 시점/적용 라인 확정 필요.", "deadlines": ["일정 미기재"], "images": ["assets/images/image25.webp"], "source": "총 필요량", "exception": false, "nextAction": "최종 수량/적용라인 확정 → 공급주체 확인 → 발주수량 확정", "primaryActionLabel": "수량·공급범위 확정", "actionTagLabels": ["수량·공급범위 확정", "SM월드 해결 / 조치"]}'::jsonb,'review',0),
('task-35-31',31,'31','Cu barrel
Nikel barrel
Sn barrel','túi vải bọc bên ngoài giỏ mạ
외부 바구니를 덮는 천 가방','L160 X H360 X W40','',12,'SMWORLD','scope','["scope", "sm_action"]'::jsonb,'{"excelRow": 35, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "Cu barrel\nNikel barrel\nSn barrel", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요수량은 있으나 시나리오별 배분이 비어 있음. 사용 시점/적용 라인 확정 필요.", "deadlines": ["일정 미기재"], "images": ["assets/images/image24.webp"], "source": "총 필요량", "exception": false, "nextAction": "최종 수량/적용라인 확정 → 공급주체 확인 → 발주수량 확정", "primaryActionLabel": "수량·공급범위 확정", "actionTagLabels": ["수량·공급범위 확정", "SM월드 해결 / 조치"]}'::jsonb,'review',0),
('task-36-32',32,'32','Cu barrel
Nikel barrel
Sn barrel','BAKET','L150 X H360 X W30','',12,'SMWORLD','master_fix','["master_fix", "sm_action", "scope"]'::jsonb,'{"excelRow": 36, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "Cu barrel\nNikel barrel\nSn barrel", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요량 시트는 BAKET 12EA이나 SMWORLD 및 공정별 필요부품 시트는 6EA. 원본 간 수량 불일치로 발주 전 필수 확인.", "deadlines": ["일정 미기재"], "images": [], "source": "총 필요량", "exception": false, "nextAction": "BAKET 12EA(총 필요량) vs 6EA(SMWORLD/공정별) 최종 발주수량 승인 → 발주목록 통일", "primaryActionLabel": "총괄표 누락·불일치 정리", "actionTagLabels": ["총괄표 누락·불일치 정리", "SM월드 해결 / 조치", "수량·공급범위 확정"]}'::jsonb,'review',0),
('task-59-33',33,'추가-1','Cu barrel / Nikel barrel / Sn barrel','Lưới rửa hàng barrel
배럴용 메쉬(세척망)','3mm','M',20,'SMWORLD','master_fix','["master_fix", "sm_action", "scope"]'::jsonb,'{"excelRow": 59, "scenario": {"H": null, "I": null, "J": null, "K": null}, "spare": null, "note": "SMWORLD 시트와 공정별 필요부품 시트에는 20m가 있으나 총 필요량 시트에는 항목 자체가 없음.", "royStock": null, "sourceStatus": "confirm", "sourceStatusLabel": "확정 필요", "reason": "총 필요량 시트 누락 후보. 발주/제작 범위에 포함되는지 확인 후 총괄표에 반영 필요.", "deadlines": ["일정 미기재"], "images": ["assets/images/image27.webp"], "source": "SMWORLD·공정별 시트만 존재", "exception": true, "nextAction": "배럴용 메쉬 20m를 총 필요량에 포함할지 승인 → 포함 시 총괄표/발주목록에 신규 반영", "primaryActionLabel": "총괄표 누락·불일치 정리", "actionTagLabels": ["총괄표 누락·불일치 정리", "SM월드 해결 / 조치", "수량·공급범위 확정"]}'::jsonb,'review',0)
on conflict (source_key) do nothing;
